language: go
sudo: false
go:
  - 1.x
install:
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b ${GOPATH}/bin v1.19.1
script:
  - golangci-lint run
  - overalls -project=github.com/mmcloughlin/adorn -- -v
  - goveralls -coverprofile=overalls.coverprofile -service=travis-ci
